function p_opt = solve_optimal_burns_fmincon(p_init, lb, ub, params)
opts = optimoptions('fmincon', ...
    'Display','iter', ...
    'Algorithm','sqp', ...
    'MaxIterations', 1000, ...
    'MaxFunctionEvaluations', 5e5, ...
    'StepTolerance', eps, ...
    'OptimalityTolerance', 1e-6);

p_opt = fmincon(@objective_dv, p_init, [], [], [], [], lb, ub, ...
    @(p) constraint_rendezvous(p, params), opts);
end
