function p_init = solve_initial_guess_fsolve(p_guess, params)
% Solve equality constraints approximately to get a physically reasonable seed.
opts = optimoptions('fsolve', ...
    'Display','iter', ...
    'Algorithm','levenberg-marquardt', ...
    'MaxIterations', 5000, ...
    'MaxFunctionEvaluations', 2e5, ...
    'FunctionTolerance', 1e-8, ...
    'StepTolerance', 1e-10);

fun = @(p) rendezvous_constraint_eq(p, params);
p_init = fsolve(fun, p_guess, opts);
end
